[sq]

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -1,3 +1,81 @@
 #!/bin/bash
 
-echo 1
+# 参考元: https://github.com/b4b4r07/dotfiles/tree/53b5ab2584645eef0c6bb0391cda0f42108387e5
+
+e_arrow() {
+    printf " \033[37;1m%s\033[m\n" "➜ $*"
+}
+
+# Set DOTPATH as default variable
+if [ -z "${DOTPATH:-}" ]; then
+    DOTPATH=~/.dotfiles; export DOTPATH
+fi
+
+dotfiles_download() {
+    if [ -d "$DOTPATH" ]; then
+        log_fail "$DOTPATH: already exists"
+        exit 1
+    fi
+
+    e_newline
+    e_header "Downloading dotfiles..."
+
+    if is_debug; then
+        :
+    else
+        if is_exists "git"; then
+            # --recursive equals to ...
+            # git submodule init
+            # git submodule update
+            git clone --recursive "$DOTFILES_GITHUB" "$DOTPATH"
+
+        elif is_exists "curl" || is_exists "wget"; then
+            # curl or wget
+            local tarball="https://github.com/b4b4r07/dotfiles/archive/master.tar.gz"
+            if is_exists "curl"; then
+                curl -L "$tarball"
+
+            elif is_exists "wget"; then
+                wget -O - "$tarball"
+
+            fi | tar xvz
+            if [ ! -d dotfiles-master ]; then
+                log_fail "dotfiles-master: not found"
+                exit 1
+            fi
+            command mv -f dotfiles-master "$DOTPATH"
+
+        else
+            log_fail "curl or wget required"
+            exit 1
+        fi
+    fi
+    e_newline && e_done "Download"
+}
+
+# A script for the file named "install"
+dotfiles_install() {
+    # 1. Download the repository
+    # ==> downloading
+    #
+    # Priority: git > curl > wget
+    dotfiles_download &&
+
+    # 2. Deploy dotfiles to your home directory
+    # ==> deploying
+    dotfiles_deploy &&
+
+    # 3. Execute all sh files within etc/init/
+    # ==> initializing
+    dotfiles_initialize "$@"
+}
+
+# if already vitalized, skip to run dotfiles_install
+if [ "${VITALIZED:=0}" = 1 ]; then
+    exit
+fi
+
+dotfiles_install "$@"
+
+e_arrow "Restarting your shell..."
+exec "${SHELL:-/bin/zsh}"
